# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: detection.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x65tection.proto\x12\tdetection\"\x85\x01\n\x10\x44\x65tectionMessage\x12\x30\n\rcustomer_flow\x18\x01 \x01(\x0b\x32\x17.detection.CustomerFlowH\x00\x12\x34\n\x0fwaiting_session\x18\x02 \x01(\x0b\x32\x19.detection.WaitingSessionH\x00\x42\t\n\x07payload\"\xf8\x02\n\x0c\x43ustomerFlow\x12\x12\n\nentry_time\x18\x01 \x01(\t\x12\x13\n\x0b\x65ntry_count\x18\x02 \x01(\x05\x12\x11\n\tage_class\x18\x03 \x01(\t\x12\x0e\n\x06gender\x18\x04 \x01(\t\x12\x13\n\x0bgender_conf\x18\x05 \x01(\x02\x12\x15\n\renter_emotion\x18\x06 \x01(\t\x12\x1a\n\x12\x65nter_emotion_conf\x18\x07 \x01(\x02\x12\x16\n\x0e\x65ntry_face_box\x18\x08 \x03(\x02\x12\x19\n\x11\x65ntry_face_vector\x18\t \x03(\x02\x12\x11\n\texit_time\x18\n \x01(\t\x12\x12\n\nexit_count\x18\x0b \x01(\x05\x12\x14\n\x0c\x65xit_emotion\x18\x0c \x01(\t\x12\x19\n\x11\x65xit_emotion_conf\x18\r \x01(\x02\x12\x15\n\rexit_face_box\x18\x0e \x03(\x02\x12\x18\n\x10\x65xit_face_vector\x18\x0f \x03(\x02\x12\x18\n\x10\x66\x61\x63\x65_match_score\x18\x10 \x01(\x02\"\x92\x01\n\x0eWaitingSession\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0b\x65ntry_frame\x18\x02 \x01(\x05\x12\x12\n\nexit_frame\x18\x03 \x01(\x05\x12\x12\n\nentry_time\x18\x04 \x01(\t\x12\x11\n\texit_time\x18\x05 \x01(\t\x12\x10\n\x08\x64uration\x18\x06 \x01(\t\x12\x12\n\nduration_s\x18\x07 \x01(\x02\"+\n\x0c\x44\x65tectionAck\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2_\n\x0f\x44\x65tectionStream\x12L\n\x10StreamDetections\x12\x1b.detection.DetectionMessage\x1a\x17.detection.DetectionAck(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DETECTIONMESSAGE']._serialized_start=31
  _globals['_DETECTIONMESSAGE']._serialized_end=164
  _globals['_CUSTOMERFLOW']._serialized_start=167
  _globals['_CUSTOMERFLOW']._serialized_end=543
  _globals['_WAITINGSESSION']._serialized_start=546
  _globals['_WAITINGSESSION']._serialized_end=692
  _globals['_DETECTIONACK']._serialized_start=694
  _globals['_DETECTIONACK']._serialized_end=737
  _globals['_DETECTIONSTREAM']._serialized_start=739
  _globals['_DETECTIONSTREAM']._serialized_end=834
# @@protoc_insertion_point(module_scope)
