"""create waiting times and entries

Revision ID: 13d0ee0c40e5
Revises: 857b83581644
Create Date: 2026-08-25 09:22:05.280672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13d0ee0c40e5'
down_revision: Union[str, Sequence[str], None] = '857b83581644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('entry_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('entry_count', sa.Integer(), nullable=True),
    sa.Column('age_class', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('gender_conf', sa.Numeric(), nullable=True),
    sa.Column('enter_emotion', sa.String(length=20), nullable=True),
    sa.Column('enter_emotion_conf', sa.Numeric(), nullable=True),
    sa.Column('entry_face_box', sa.Text(), nullable=True),
    sa.Column('entry_face_vector', sa.Text(), nullable=True),
    sa.Column('exit_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('exit_count', sa.Integer(), nullable=True),
    sa.Column('exit_emotion', sa.String(length=20), nullable=True),
    sa.Column('exit_emotion_conf', sa.Numeric(), nullable=True),
    sa.Column('exit_face_box', sa.Text(), nullable=True),
    sa.Column('exit_face_vector', sa.Text(), nullable=True),
    sa.Column('face_match_score', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('waiting_times',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('entry_frame', sa.Integer(), nullable=True),
    sa.Column('exit_frame', sa.Integer(), nullable=True),
    sa.Column('entry_time', sa.String(length=20), nullable=True),
    sa.Column('exit_time', sa.String(length=20), nullable=True),
    sa.Column('duration', sa.String(length=20), nullable=True),
    sa.Column('duration_s', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.drop_index(op.f('ix_customer_flow_branch_id'), table_name='customer_flow')
    op.drop_index(op.f('ix_customer_flow_status'), table_name='customer_flow')
    op.drop_table('customer_flow')
    op.drop_index(op.f('ix_waiting_time_branch_id'), table_name='waiting_time')
    op.drop_index(op.f('ix_waiting_time_camera_id'), table_name='waiting_time')
    op.drop_index(op.f('ix_waiting_time_tracking_id'), table_name='waiting_time')
    op.drop_table('waiting_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waiting_time',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('branch_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('camera_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tracking_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entry_frame', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exit_frame', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('entry_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('exit_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('waiting_time_pkey'))
    )
    op.create_index(op.f('ix_waiting_time_tracking_id'), 'waiting_time', ['tracking_id'], unique=False)
    op.create_index(op.f('ix_waiting_time_camera_id'), 'waiting_time', ['camera_id'], unique=False)
    op.create_index(op.f('ix_waiting_time_branch_id'), 'waiting_time', ['branch_id'], unique=False)
    op.create_table('customer_flow',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('age_class', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('branch_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entry_camera_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('entry_tracking_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('entry_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('gender_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('entry_emotion', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('entry_emotion_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('entry_face_vector', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True),
    sa.Column('entry_face_box', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('exit_camera_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('exit_tracking_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('exit_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('exit_emotion', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('exit_emotion_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('exit_face_vector', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True),
    sa.Column('exit_face_box', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('face_match_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('customer_flow_pkey'))
    )
    op.create_index(op.f('ix_customer_flow_status'), 'customer_flow', ['status'], unique=False)
    op.create_index(op.f('ix_customer_flow_branch_id'), 'customer_flow', ['branch_id'], unique=False)
    op.drop_table('waiting_times')
    op.drop_table('entries')
    # ### end Alembic commands ###
