"""add customer flow and waiting sessions

Revision ID: 857b83581644
Revises: 
Create Date: 2026-08-25 07:04:31.431457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '857b83581644'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waiting_time',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.String(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('tracking_id', sa.String(), nullable=False),
    sa.Column('entry_frame', sa.Integer(), nullable=True),
    sa.Column('exit_frame', sa.Integer(), nullable=True),
    sa.Column('entry_time', sa.DateTime(), nullable=True),
    sa.Column('exit_time', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waiting_time_branch_id'), 'waiting_time', ['branch_id'], unique=False)
    op.create_index(op.f('ix_waiting_time_camera_id'), 'waiting_time', ['camera_id'], unique=False)
    op.create_index(op.f('ix_waiting_time_tracking_id'), 'waiting_time', ['tracking_id'], unique=False)
    op.drop_table('waiting_times')
    op.add_column('customer_flow', sa.Column('branch_id', sa.String(), nullable=False))
    op.add_column('customer_flow', sa.Column('entry_camera_id', sa.String(), nullable=True))
    op.add_column('customer_flow', sa.Column('entry_tracking_id', sa.String(), nullable=True))
    op.add_column('customer_flow', sa.Column('entry_time', sa.DateTime(), nullable=True))
    op.add_column('customer_flow', sa.Column('gender_confidence', sa.Float(), nullable=True))
    op.add_column('customer_flow', sa.Column('entry_emotion', sa.String(), nullable=True))
    op.add_column('customer_flow', sa.Column('entry_emotion_confidence', sa.Float(), nullable=True))
    op.add_column('customer_flow', sa.Column('entry_face_vector', postgresql.ARRAY(sa.Float()), nullable=True))
    op.add_column('customer_flow', sa.Column('entry_face_box', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('customer_flow', sa.Column('exit_camera_id', sa.String(), nullable=True))
    op.add_column('customer_flow', sa.Column('exit_tracking_id', sa.String(), nullable=True))
    op.add_column('customer_flow', sa.Column('exit_time', sa.DateTime(), nullable=True))
    op.add_column('customer_flow', sa.Column('exit_emotion', sa.String(), nullable=True))
    op.add_column('customer_flow', sa.Column('exit_emotion_confidence', sa.Float(), nullable=True))
    op.add_column('customer_flow', sa.Column('exit_face_vector', postgresql.ARRAY(sa.Float()), nullable=True))
    op.add_column('customer_flow', sa.Column('exit_face_box', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('customer_flow', sa.Column('face_match_score', sa.Float(), nullable=True))
    op.add_column('customer_flow', sa.Column('status', sa.String(), nullable=False))
    op.create_index(op.f('ix_customer_flow_branch_id'), 'customer_flow', ['branch_id'], unique=False)
    op.create_index(op.f('ix_customer_flow_status'), 'customer_flow', ['status'], unique=False)
    op.drop_column('customer_flow', 'event_time')
    op.drop_column('customer_flow', 'count')
    op.drop_column('customer_flow', 'created_at')
    op.drop_column('customer_flow', 'event_type')
    op.drop_column('customer_flow', 'emotion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_flow', sa.Column('emotion', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('customer_flow', sa.Column('event_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('customer_flow', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('customer_flow', sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('customer_flow', sa.Column('event_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_customer_flow_status'), table_name='customer_flow')
    op.drop_index(op.f('ix_customer_flow_branch_id'), table_name='customer_flow')
    op.drop_column('customer_flow', 'status')
    op.drop_column('customer_flow', 'face_match_score')
    op.drop_column('customer_flow', 'exit_face_box')
    op.drop_column('customer_flow', 'exit_face_vector')
    op.drop_column('customer_flow', 'exit_emotion_confidence')
    op.drop_column('customer_flow', 'exit_emotion')
    op.drop_column('customer_flow', 'exit_time')
    op.drop_column('customer_flow', 'exit_tracking_id')
    op.drop_column('customer_flow', 'exit_camera_id')
    op.drop_column('customer_flow', 'entry_face_box')
    op.drop_column('customer_flow', 'entry_face_vector')
    op.drop_column('customer_flow', 'entry_emotion_confidence')
    op.drop_column('customer_flow', 'entry_emotion')
    op.drop_column('customer_flow', 'gender_confidence')
    op.drop_column('customer_flow', 'entry_time')
    op.drop_column('customer_flow', 'entry_tracking_id')
    op.drop_column('customer_flow', 'entry_camera_id')
    op.drop_column('customer_flow', 'branch_id')
    op.create_table('waiting_times',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entry_frame', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exit_frame', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entry_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('exit_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('duration_s', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('waiting_times_pkey'))
    )
    op.drop_index(op.f('ix_waiting_time_tracking_id'), table_name='waiting_time')
    op.drop_index(op.f('ix_waiting_time_camera_id'), table_name='waiting_time')
    op.drop_index(op.f('ix_waiting_time_branch_id'), table_name='waiting_time')
    op.drop_table('waiting_time')
    # ### end Alembic commands ###
